name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test 
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 Thanks for reporting!'
          })
    - name: Extract tag name for docker image
      id: tag
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          return git describe --abbrev=0;
    - name: Echo
      run: echo ${{ steps.tag.outputs.result }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag andreaavanzi/docker-angular-cli:${{ steps.tag.outputs.result }}
    - name: Push the Docker image
      run: docker push andreaavanzi/alpine-awscli-kubectl:${{ steps.tag.outputs.result }}
