name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: olegtarasov/get-tag@v2
        id: tagName
      - name: Yet another step # Environment variabl usage example
        run: |
          docker build . --file Dockerfile --tag andreaavanzi/docker-angular-cli:$GIT_TAG_NAME
      - name: Push the Docker image
        run: docker push andreaavanzi/alpine-awscli-kubectl:$GIT_TAG_NAME
